spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev
    username: dev
    password: dev

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  security:
    jwt:
      secret: "sea-jwt-security-secret-senha-32-caracteres-version"
      expiration-ms: 86400000